
if [[ -o interactive ]]; then
    # Setup Antigen
    source ~/.antigen/antigen.zsh
    antigen init ~/.antigenrc

    # Configure aliases
    source ~/.aliases

    # Setup starship prompt
    eval "$(starship init zsh)"
fi

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacsclient'
else
  export EDITOR='emacsclient'
fi

#ripgrep
export RIPGREP_CONFIG_PATH=~/.ripgreprc

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
