
if [[ -o interactive ]]; then
    source <(antibody init)
    antibody bundle < ~/.zsh_plugins.txt
    ZSH=$(antibody path ohmyzsh/ohmyzsh)
fi

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacsclient'
else
  export EDITOR='emacsclient'
fi

#ripgrep
export RIPGREP_CONFIG_PATH=~/.ripgreprc


#Plugins
if [[ -o interactive ]]; then
    source ~/.dotfiles/zsh/funcs.zsh
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
fi

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
