format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# Bump default timeout since git is slooow on windows
command_timeout = 1000

[directory]
style = "blue"
truncation_symbol = "../"
truncate_to_repo = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "bold purple"

[git_commit]
format='[@ $hash$tag]($style) '
commit_hash_length=7
style = "bold purple"

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'
style = "cyan"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
ignore_submodules = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "yellow bold"
